### ISSUE TITLE
I used xrdp+xorg in ubuntu 18.04, and the remote connection is normal, but is it not supported to bring in external Chinese?

### ISSUE THREAD

**Issue by MagicStarTrace** [neutrinolabs/xorgxrdp#196] opened 2021-09-09 07:15 UTC
xrdp: A Remote Desktop Protocol server.
Copyright (C) Jay Sorg 2004-2014
See http://www.xrdp.org for more information.
Version 0.9.5

xrdp start command：
root@#/usr/lib/xorg/Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log

Auxiliary Support Packages Installed：
apt install -y language-pack-zh-hans fonts-droid-fallback ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-ukai fonts-arphic-uming

In the same environment of Chinese and related dependencies, vnc is a device that can bring external Chinese into the remote ubuntu 18.04 system

I currently use the input method in ubuntu, but I hope that the Chinese from the external client can be brought into the ubuntu system

If I want to achieve it, what should I do?

Thank You

**Comment by matt335672** [comment] 2021-09-09 08:57
Duplicate of neutrinolabs/xrdp#1990

**Closed as completed by matt335672** 2021-09-09 08:57 UTC
